name: CI

on:
  push:
    branches: [master, buildx]
  pull_request:
    branches: [master, buildx]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # node
      - uses: actions/setup-node@v1
        with:
          node-version: '10.18'
      - run: yarn install
      - run: yarn build
      # docker
      - name: Set Up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker Login
        run: docker login -u vbstreetz -p ${{ secrets.dockerhub }}
      - name: Run Buildx
        run: ./buildx.sh
